api.http.host: "127.0.0.1"
pipeline.ecs_compatibility: v8
queue.type: persisted
path.queue: /usr/share/logstash/data/queue
queue.max_bytes: 1gb
queue.checkpoint.writes: 1024
dead_letter_queue.enable: false
config.reload.automatic: false
