-- Plaintext credentials must not remain at rest after the application stops
-- accepting them.  Record only the account id and reason, then replace the
-- value with a random, unusable marker.  The normal OTP password-reset flow
-- restores access; no password value is copied into this audit table.
CREATE TABLE IF NOT EXISTS tbl_tai_khoan_can_dat_lai_mat_khau (
    user_id VARCHAR(64) NOT NULL,
    reason VARCHAR(80) NOT NULL,
    detected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reset_completed_at DATETIME NULL,
    PRIMARY KEY (user_id),
    KEY idx_password_reset_required_open (reset_completed_at, detected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO tbl_tai_khoan_can_dat_lai_mat_khau (user_id, reason)
SELECT id, 'LEGACY_NON_BCRYPT_PASSWORD'
FROM tbl_nguoi_dung
WHERE password IS NOT NULL
  AND NOT (
      password LIKE '$2a$%'
      OR password LIKE '$2b$%'
      OR password LIKE '$2y$%'
      OR password LIKE '{bcrypt-sha256}$2a$%'
      OR password LIKE '{bcrypt-sha256}$2b$%'
      OR password LIKE '{bcrypt-sha256}$2y$%'
  );

-- UUID() is generated by MySQL for each affected row.  It is intentionally not
-- derived from the legacy value, so a database leak cannot be used to recover
-- the former plaintext password.
UPDATE tbl_nguoi_dung
SET password = CONCAT('{reset-required}', REPLACE(UUID(), '-', ''))
WHERE password IS NOT NULL
  AND NOT (
      password LIKE '$2a$%'
      OR password LIKE '$2b$%'
      OR password LIKE '$2y$%'
      OR password LIKE '{bcrypt-sha256}$2a$%'
      OR password LIKE '{bcrypt-sha256}$2b$%'
      OR password LIKE '{bcrypt-sha256}$2y$%'
  );
