param(
    [Parameter(Mandatory = $true)]
    [string[]]$CsvPath,
    [string]$SqlPath = "C:\PBL3\db-init\product_images_seed.sql"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Escape-SqlLiteral {
    param([AllowNull()][string]$Value)
    if ($null -eq $Value) {
        return ""
    }

    return $Value.Replace("'", "''")
}

function Normalize-Url {
    param([string]$Value)

    if ([string]::IsNullOrWhiteSpace($Value)) {
        return ""
    }

    return $Value.Trim().Replace("\", "/")
}

function Resolve-ImageUrl {
    param([pscustomobject]$Row)

    $directUrl = Normalize-Url $Row.hinh_anh_url
    if (-not [string]::IsNullOrWhiteSpace($directUrl)) {
        return $directUrl
    }

    $localPath = ""
    if ($null -ne $Row.local_image_path) {
        $localPath = [string]$Row.local_image_path
    }
    $localPath = $localPath.Trim()
    if ([string]::IsNullOrWhiteSpace($localPath)) {
        return ""
    }

    $workspaceRoot = "C:\PBL3"
    $absolutePath = if ([System.IO.Path]::IsPathRooted($localPath)) {
        $localPath
    } else {
        Join-Path $workspaceRoot $localPath
    }

    if (-not (Test-Path -LiteralPath $absolutePath)) {
        throw "Image file not found for SKU $($Row.sku): $absolutePath"
    }

    $relativePath = $absolutePath.Substring($workspaceRoot.Length).TrimStart('\')
    return "/" + $relativePath.Replace("\", "/")
}

$csvFiles = New-Object System.Collections.Generic.List[string]
foreach ($path in $CsvPath) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "CSV path not found: $path"
    }

    $item = Get-Item -LiteralPath $path
    if ($item.PSIsContainer) {
        Get-ChildItem -LiteralPath $item.FullName -Filter "batch-*.csv" | Sort-Object Name | ForEach-Object {
            $csvFiles.Add($_.FullName)
        }
    } else {
        $csvFiles.Add($item.FullName)
    }
}

if ($csvFiles.Count -eq 0) {
    throw "No CSV files were resolved from the supplied path(s)."
}

$updateMap = @{}
foreach ($csvFile in $csvFiles) {
    $rows = Import-Csv -LiteralPath $csvFile
    if (-not $rows) {
        continue
    }

    foreach ($row in $rows) {
        $sku = ""
        if ($null -ne $row.sku) {
            $sku = [string]$row.sku
        }
        $sku = $sku.Trim()
        if ([string]::IsNullOrWhiteSpace($sku)) {
            continue
        }

        $imageUrl = Resolve-ImageUrl $row
        $sourcePageUrl = ""
        if ($null -ne $row.source_page_url) {
            $sourcePageUrl = Normalize-Url ([string]$row.source_page_url)
        }

        if ([string]::IsNullOrWhiteSpace($imageUrl) -and [string]::IsNullOrWhiteSpace($sourcePageUrl)) {
            continue
        }

        $updateMap[$sku] = [pscustomobject]@{
            sku = $sku
            image_url = $imageUrl
            source_page_url = $sourcePageUrl
        }
    }
}

$updates = @(
    $updateMap.GetEnumerator() |
        Sort-Object Name |
        ForEach-Object { $_.Value }
)

$lines = @(
    "-- Auto-generated by scripts/Sync-ProductImages.ps1",
    "USE flare_fitness;",
    ""
)

if ($updates.Count -eq 0) {
    $lines += "-- No product image updates were provided."
} else {
    foreach ($update in $updates) {
        $imageSql = if ([string]::IsNullOrWhiteSpace($update.image_url)) {
            "hinh_anh_url = hinh_anh_url"
        } else {
            "hinh_anh_url = '" + (Escape-SqlLiteral $update.image_url) + "'"
        }

        $sourceSql = if ([string]::IsNullOrWhiteSpace($update.source_page_url)) {
            "link_san_pham = link_san_pham"
        } else {
            "link_san_pham = '" + (Escape-SqlLiteral $update.source_page_url) + "'"
        }

        $lines += "UPDATE tbl_san_pham"
        $lines += "SET $imageSql, $sourceSql"
        $lines += "WHERE sku = '" + (Escape-SqlLiteral $update.sku) + "';"
        $lines += ""
    }
}

$directory = Split-Path -Path $SqlPath -Parent
if (-not [string]::IsNullOrWhiteSpace($directory)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
}

Set-Content -LiteralPath $SqlPath -Value $lines -Encoding UTF8
Write-Host ("Wrote {0} updates to {1}" -f $updates.Count, $SqlPath)
