CREATE TABLE IF NOT EXISTS tbl_su_kien_hanh_vi_nguoi_dung (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NULL,
    session_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    page_type VARCHAR(50) NULL,
    page_key VARCHAR(255) NULL,
    product_id VARCHAR(64) NULL,
    order_id VARCHAR(64) NULL,
    category_key VARCHAR(100) NULL,
    brand_key VARCHAR(100) NULL,
    search_keyword VARCHAR(255) NULL,
    price_bucket VARCHAR(50) NULL,
    price_value DECIMAL(15,2) NULL,
    quantity INT NULL,
    duration_seconds INT NULL,
    metadata_json JSON NULL,
    ngay_tao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_behavior_created_time (ngay_tao),
    INDEX idx_behavior_user_time (user_id, ngay_tao),
    INDEX idx_behavior_session_time (session_id, ngay_tao),
    INDEX idx_behavior_event_time (event_type, ngay_tao),
    INDEX idx_behavior_product_time (product_id, ngay_tao),
    INDEX idx_behavior_category_time (category_key, ngay_tao),
    INDEX idx_behavior_brand_time (brand_key, ngay_tao)
);

CREATE TABLE IF NOT EXISTS tbl_ho_so_hanh_vi_nguoi_dung (
    user_id VARCHAR(64) PRIMARY KEY,
    favorite_category VARCHAR(100) NULL,
    favorite_brand VARCHAR(100) NULL,
    preferred_price_bucket VARCHAR(50) NULL,
    price_min DECIMAL(15,2) NULL,
    price_max DECIMAL(15,2) NULL,
    top_categories_json JSON NULL,
    top_brands_json JSON NULL,
    top_keywords_json JSON NULL,
    last_viewed_product_id VARCHAR(64) NULL,
    total_interactions INT NOT NULL DEFAULT 0,
    average_stay_seconds INT NOT NULL DEFAULT 0,
    total_purchases INT NOT NULL DEFAULT 0,
    ngay_tao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_behavior_profile_category (favorite_category),
    INDEX idx_behavior_profile_brand (favorite_brand)
);
